SPRING_API_URL: const
MEAN_API_URL: const
TRACKING_API_URL: const
TRACKING_API_URL_PAGE: const
TRACKING_TOTAL_PAGE_API: const
SORT_TRACKING_API: const
STATISTICS_API_URL: const
PIE_CHART_API_URL: const
PAGE_ACCESS_API_URL: const
PAGE_ACCESS_IP_API_URL: const
PAGE_ACCESS_MEMBER_API_URL: const
COLUNM_CHART_API_URL: const
IP_COLUNM_CHART_API_URL: const
MEMBER_COLUNM_CHART_API_URL: const
SEARCH_API = TRACKING_API_URL: const
TOTAL_PAGE_SEARCH_API: const
TRACKING_SEARCH_API: const
TOTAL_PAGE_DISPLAY: const
