
 - DATABASE
 - DB_HOST
 - DB_PORT

 - SPRING_SERVER_URL
 - SPRING_API_URL

 - RESTAURANT_API
 - ROOM_API
 - ROOM_NAME_API


 + DB_CONNECTION
 + DB_CONNECT_SUCCESS
 + SERCRET
 + PORT
 + RESOURCE
 + VIEW
 + VIEW_FILE_EXTENSION
 + ANGULAR_DIR
 + LOGGER
 + PAGE404
 + APP_RUNNING_RESULT
 + ERROR_MES
 + SUCCESS_MES

 + MAIL_SERVICE
 + MAIL_USER
 + MAIL_AUTH
 + HEADER_MAIL
 + FOOTER_MAIL

 + USER_API
 + ACTIVITY_API
 + FOLLOW_USER_API

 + RESTAURANT_API_URL
 + ROOM_API_URL
 + ROOM_NAME_API_URL


 + SIGNUP_SUCESS
 + TKS_SIGNUP
 + ACCOUNT_INIT
 + BALANCE_INIT
 + SIGNUP_DETAIL
 + NO_RES
 + ACCOUNT_USED
 + SIGN_UP_FAIL
 + EMAIL_TAKEN
 + SIGNUP_ERR
 + SIGNUP_INVALID
 + CHANGE_PW_FAIL
 + CHANGE_PW_SUCCESS
 + CHANGE_PW_DETAIL
 + CHANGE_PW_NOTE
 + CHANGE_PW_CONTENT

 + INPUT_USERNAME
 + INPUT_PASSWORD
 + INVALID_PASSWORD
 + INPUT_EMAIL
 + INPUT_NEW_PASSWORD
 + CONFIRM_PW
 + PW_NOT_CHANGE
 + INPUT_NAME
 + INPUT_PHONE
 + PHONE_INVALID
 + INPUT_ADDRESS
 + CLICK_REGISTER
 + CLICK_ChANGE_PW
 + LOGIN_SUCCESS
 + LOGIN_FAIL
 + CLICK_LOGIN
 + CLICK_LOGOUT
 + INVALID_USERNAME
 + WRONG_PW
 + ACTIVITY_RESPONSE_STATUS
 + DEFAULT_IP
 + DEFAULT_ROOM_PRICE
 + DEFAULT_ROOM_SIZE
 + DEFAULT_ROOM_AMINITY
 + NUM_TRACKING_EACH_PAGE