 - express: express
 - router: router
 - ctrl: controller
 
 - getActivity(): GET URL('/')
 - getActivityByID(id): GET URL('/:id')
 - getActivityByUserName(username): GET URL('/username/:username')
 - getActivityFeedBackRoom(id): GET URL('/feedback-room/:id')
 - getNotResponseActivity(id): GET URL('/response/not-yet')
 - seenAndGetNotification(id): GET URL('/seen-notification/:id')
 - replyAndGetNotification(id): GET URL('/reply-notification/:id')
 - postActivity(): POST URL('/')
 - deleteActivity(id): DELETE URL('/:id')