AppRoute
--
 - express: express
 - router: router
 - passport: passport
 - ctrl: controller
--
 -login: <<get>>
 -login: <<post>>
 -loginsuccess: <<get>>
 -logout: <<get>>
 -register: <<get>>
 -register: <<post>>
 -change-password: <<get>>
 -change-password: <<post>>